# Generated by Django 3.0.8 on 2020-07-21 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=17)),
                ('ip', models.CharField(max_length=14)),
                ('lastSeen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
