# Generated by Django 3.0.8 on 2020-07-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arko', '0002_auto_20200721_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
